# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 10240,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 2048, # Megabytes
			:port => 2
		},
		:sata3 => {
                        :dfile => './sata3.vdi',
                        :size => 1024, # Megabytes
			:port => 3
		},
		:sata4 => {
                        :dfile => './sata4.vdi',
                        :size => 1024, # Megabytes
			:port => 4
		},
		:sata5 => {
                        :dfile => './sata5.vdi',
                        :size => 40960, # Megabytes
			:port => 5
		},
		:sata6 => {
                        :dfile => './sata6.vdi',
                        :size => 40960, # Megabytes
			:port => 6
		},
		:sata7 => {
                        :dfile => './sata7.vdi',
                        :size => 40960, # Megabytes
			:port => 7
		},
		:sata8 => {
                        :dfile => './sata8.vdi',
                        :size => 40960, # Megabytes
			:port => 8
		},
		:sata9 => {
                        :dfile => './sata9.vdi',
                        :size => 40960, # Megabytes
			:port => 9
		},
		:sata10 => {
                        :dfile => './sata10.vdi',
                        :size => 40960, # Megabytes
			:port => 10
		}

	}

		
  },
}

Vagrant.configure("2") do |config|
  config.vm.box_version = "1804.02"
  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]
		  box.vm.provider :virtualbox do |v|
		    	  v.name = "Exercise3"
		    	  v.customize ["modifyvm", :id, "--cpus", 8]
		  end

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "4096"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
  	  SHELL

     
      end

  end
end






