# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = true
  config.vbguest.auto_update = false
  
  config.vm.define "server1" do |server|
    server.vm.hostname = "server1"
    server.vm.network "private_network", ip: "192.168.10.10"
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "server1.yml"
    end
  end
  
  config.vm.define "server2" do |server|
    server.vm.hostname = "server2"
    server.vm.network "private_network", ip: "192.168.10.30"
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "server2.yml"
    end
  end
  
  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.10.20"
    client.vm.provision "ansible" do |ansible|
      ansible.playbook = "client.yml"
    end
  end
  
  
end
